import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Camera as Instagram,Menu,Phone,X} from 'lucide-react';
import './styles.css';

const work=[['work-before-exterior.png','Exterior refresh','Before'],['work-after-exterior.png','Exterior refresh','After'],['work-before-interior.png','Interior reset','Before'],['work-after-interior.png','Interior reset','After'],['work-foam.png','Safe wash','Recent'],['work-blue.png','Full valet','Recent'],['work-wheel.png','Wheel care','Recent'],['work-porsche.png','Luxury finish','Recent']];
const services=[['01','The Essential Valet','A meticulous maintenance clean that keeps your car looking its best.','From £45'],['02','The Full Valet','A deep interior and exterior reset for the cars that need a little more love.','From £95'],['03','The Signature Detail','The complete CB experience — premium products, precision finish, lasting protection.','From £175']];
function App(){const [menu,setMenu]=useState(false); const [book,setBook]=useState(false); return <div className="app">
<header><a className="brand" href="#top"><img src="/logo.png"/><span>CB <b>VALETING</b></span></a><nav className={menu?'open':''}><a href="#services">Services</a><a href="#work">Recent work</a><a href="#about">About us</a><a href="#contact">Contact</a></nav><button className="nav-cta" onClick={()=>setBook(true)}>Book a valet <ArrowRight size={17}/></button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main id="top"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> PREMIUM MOBILE VALETING</div><h1>Leave the dirt.<br/><em>Keep the shine.</em></h1><p>Luxury mobile valeting brought to your doorstep. A meticulous finish, wherever you are in Lincolnshire & North Yorkshire.</p><div className="hero-actions"><button className="gold" onClick={()=>setBook(true)}>Book your valet <ArrowRight size={18}/></button><a className="text-link" href="#work">See our recent work <ArrowRight size={16}/></a></div><div className="proof"><div className="avatars"><span>CB</span><span>★</span><span>✓</span></div><div><strong>Trusted by local drivers</strong><small>Premium care. Every time.</small></div></div></div><div className="hero-image"><picture><source media="(max-width: 1100px)" srcSet="/hero-mobile.png"/><img src="/hero.png"/></picture><div className="image-tag"><span>CB</span><small>DETAILING<br/>DONE RIGHT</small></div></div></section>
<section className="ticker"><span>PREMIUM PRODUCTS</span><i>✦</i><span>ATTENTION TO DETAIL</span><i>✦</i><span>WE COME TO YOU</span><i>✦</i><span>LINCOLNSHIRE & NORTH YORKSHIRE</span></section>
<section className="intro" id="about"><div className="section-label">01 / WHY CB VALETING</div><div><h2>More than a clean.<br/><em>A proper finish.</em></h2><p>We believe your car deserves more than a quick wash. CB Valeting brings careful, considered detailing to your home or workplace — so you get back a car that feels genuinely looked after.</p><a href="#services" className="text-link">What we do <ArrowRight size={16}/></a></div></section>
<section className="services" id="services"><div className="service-head"><div><div className="section-label">02 / OUR SERVICES</div><h2>Pick your level<br/><em>of clean.</em></h2></div><p>Every valet is tailored to your car, your schedule and the finish you want. No rushed jobs. No shortcuts.</p></div><div className="service-grid">{services.map((s,i)=><article className={i===1?'featured':''} key={s[0]}><div className="service-no">{s[0]} <span>{i===1?'MOST POPULAR':''}</span></div><h3>{s[1]}</h3><p>{s[2]}</p><div className="service-bottom"><strong>{s[3]}</strong><button onClick={()=>setBook(true)}><ArrowRight size={18}/></button></div></article>)}</div></section>
<section className="work" id="work"><div className="work-head"><div><div className="section-label">03 / RECENT WORK</div><h2>The proof is<br/><em>in the finish.</em></h2></div><a className="text-link" href="https://www.instagram.com/cb_valeting_ltd/" target="_blank">Follow along on Instagram <Instagram size={17}/></a></div><div className="gallery">{work.map((w,i)=><div className="tile" key={w[0]}><img src={'/'+w[0]}/><div className="tile-overlay"><span>{w[2]}</span><strong>{w[1]}</strong></div></div>)}</div></section>
<section className="quote"><div className="quote-mark">“</div><blockquote>“A proper professional job from start to finish. The car looked brand new — and I didn’t even have to leave the house.”</blockquote><div className="stars">★★★★★ <span>— Local customer</span></div></section>
<section className="cta" id="contact"><div><div className="section-label">04 / READY WHEN YOU ARE</div><h2>Your car's next<br/><em>best day starts here.</em></h2></div><button className="gold" onClick={()=>setBook(true)}>Book a valet <ArrowRight size={18}/></button></section>
</main><footer><div className="brand"><img src="/logo.png"/><span>CB <b>VALETING</b></span></div><p>Premium mobile valeting across Lincolnshire<br/>& North Yorkshire.</p><div className="footer-links"><a href="https://www.instagram.com/cb_valeting_ltd/" target="_blank"><Instagram size={18}/> Instagram</a><a href="#contact"><Phone size={17}/> Get in touch</a></div><small>© 2025 CB Valeting LTD</small></footer>
{book&&<div className="modal" onClick={()=>setBook(false)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setBook(false)}><X/></button><div className="section-label">BOOK A VALET</div><h2>Let's get your car<br/><em>looking its best.</em></h2><p>Send us a few details and we'll come back to you with availability.</p><input placeholder="Your name"/><input placeholder="Phone number"/><select><option>Choose a service</option><option>The Essential Valet</option><option>The Full Valet</option><option>The Signature Detail</option></select><button className="gold">Request booking <ArrowRight size={18}/></button></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
